import 'QuestionComp.dart';

final List<QuestionData> questionsList = [
  QuestionData("1. Fabric is properly sewed. (Check edges of the fabric)"),
  QuestionData("2. Hook and loop of the band are properly stitched"),
  QuestionData("3. Right band Turning on"),
  QuestionData("4. Left band Turning on"),
  QuestionData("5. Bands are held in proper orientation (band arrow pointing down)"),
  QuestionData("6. Right band LEDs working"),
  QuestionData("7. Left band LEDs working"),
  QuestionData("8. Right band both vibration motors are vibrating"),
  QuestionData("9. Left band both vibration motors are vibrating"),
  QuestionData("10. Bands went to open loop mode"),
  QuestionData("11. Band stopped vibrating when right band is turned to 90 degree"),
  QuestionData("12. Bands connect with app"),
  QuestionData("13. Right band magnitude is changing via app"),
  QuestionData("14. Left band magnitude is changing via app"),
  QuestionData("15. Frequency of the bands is changing via app"),
  QuestionData("16. No vib/high frequency mode is working as intended"),
  QuestionData("17. Swing phase continuous mode is working as intended"),
  QuestionData("18. Swing phase burst mode is working as intended"),
  QuestionData("19. Stance phase continuous mode is working as intended"),
  QuestionData("20. Stance phase burst mode is working as intended"),
  QuestionData("21. Open loop mode is working as intended"),
  QuestionData("22. Football game is working without major lag"),
  QuestionData("23. Both positive and negative angles are working as intended"),
  QuestionData("24. Swing game is working without major lag"),
  QuestionData("25. Fish game is working without major lag"),
  QuestionData("26. Reset the magnitude and frequency"),
];